Feature : 게시물 작성 페이지
kit-SE-Project/SE-FE pull request #4
Opened 2023-03-30 11:15 UTC by lcy042000

## 개요

notion : 
- https://www.notion.so/d480ee1d48ba4dcb8fad099fc051908e?pvs=4
- https://www.notion.so/5df9e5dac87644d78ad552a9b510cfa3?pvs=4
<br>
<br>

## 작업내용

- 공지사항 게시글 작성 페이지
- 자유게시판 게시글 작성 페이지
- 아카이브 게시글 작성 페이지

<br>
<br>

## 참고 내용

- ckeditor title plugin에서 title의 크기가 본문 크기와 똑같은 버그
- 파일 업로드 UI 디자인 수정 필요할 듯
- 로그인 후 익명 글 작성으로 변경 시 일부 수정 필요

2023-04-04 18:48 UTC, brobac requested changes

2023-04-04 18:48 UTC, brobac commented on apps/se-board/src/styles/chakraTheme.ts
> +      color: semanticColors["primary-content"],
danger에 semanticColor로는 danger가 들어가는게 맞는 거 같아 
semanticColors["error-content"] 의 색을 white로 바꾸면 좋을 듯

2023-04-04 18:48 UTC, brobac commented on apps/se-board/src/components/writing/CategoryAndPrivacySetting.tsx
> +  const { CATEGORY_OPTIONS } = props;
함수에서 바로 디스트럭처링 해서받을 수 있어
```javascript
export const CategoryAndPrivacySeeting = ({CATEGORY_OPTIONS}:{ CATEGORY_OPTIONS : Array<id:string; value:string}}>) => {...
```
타입 부분을 interface로 분리해서 작성하는 방법도 있어
그리고 props는 카멜케이스로 통일하면 좋을 듯

2023-04-04 18:48 UTC, brobac commented on apps/se-board/src/components/writing/FileUploader.tsx
https://dribbble.com/shots/15156538-Image-storage
위에 거 처럼 버튼은 숨기고 첨부파일 업로드 영역에 드래그 앤 드롭 하거나 영역을 클릭하면 finder를 띄우는게 좀 더 이뻐보이는데 어때?

2023-04-14 10:31 UTC, lcy042000 commented on apps/se-board/src/components/writing/CategoryAndPrivacySetting.tsx
> +interface category_option {
인터페이스 부분은 파스칼 케이스로 통일할게

2023-04-14 10:32 UTC, lcy042000 commented on apps/se-board/src/components/writing/CategoryAndPrivacySetting.tsx
> +const NOTICE_CATEGORY_OPTIONS: ReadonlyArray<category_option> = [
배열은 []로 통일하도록 바꿀게

2023-04-14 10:33 UTC, lcy042000 commented on apps/se-board/src/components/writing/CategoryAndPrivacySetting.tsx
> +      <InputRightElement width="4.5rem">
아이콘으로 변경한 다음 헷갈릴 수 있을 것 같아서 Tooltip으로 의미 전달하도록 수정했어

2023-04-14 10:45 UTC, lcy042000 commented on apps/se-board/src/components/writing/CategoryAndPrivacySetting.tsx
> +    const { innerHTML } = e.currentTarget;
value attribute가 없어서 innerHTML을 사용하게 됐어

2023-04-14 10:53 UTC, lcy042000 commented on apps/se-board/src/components/writing/CategoryAndPrivacySetting.tsx
> +              <Heading as="h4" size="sm" pb="5px">
okay!

2023-04-14 11:06 UTC, lcy042000 commented on apps/se-board/src/components/writing/CategoryAndPrivacySetting.tsx
> +                  color={active === "전체" ? openColors.white : ""}
button varient 수정했어

2023-04-14 11:11 UTC, lcy042000 commented on apps/se-board/src/components/writing/CategoryAndPrivacySetting.tsx
> +      borderBottomWidth="0.6px"
수정했어!

2023-04-14 11:16 UTC, lcy042000 commented on apps/se-board/src/components/writing/CategoryAndPrivacySetting.tsx
> +          </Button>
수정했어!

2023-04-14 11:21 UTC, lcy042000 commented on apps/se-board/src/components/writing/FileUploader.tsx
> +                  <Button
수정했어!

2023-04-14 11:36 UTC, lcy042000 commented on apps/se-board/src/components/writing/AnonymousRegister.tsx
> +      maxW="984px"
수정했어!

2023-04-14 11:38 UTC, lcy042000 commented on apps/se-board/src/styles/chakraTheme.ts
> +      color: semanticColors["primary-content"],
okay!

2023-04-14 11:59 UTC, lcy042000 commented on apps/se-board/src/components/writing/FileUploader.tsx
수정했는데 확인해줘

2023-04-15 18:51 UTC, brobac approved these changes

2023-04-15 18:51 UTC, merged